/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tm325716
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    
    public boolean gagne(){
        if(ZoneIcon.getName().equals(ZoneMetier.getName()))
            return true;
        else return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        peintre = new javax.swing.JButton();
        patissier = new javax.swing.JButton();
        coiffeur = new javax.swing.JButton();
        sculpteur = new javax.swing.JButton();
        marin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        ZoneIcon = new javax.swing.JButton();
        ZoneMetier = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Resultat = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Titre = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Isculpteur = new javax.swing.JButton();
        Imarin = new javax.swing.JButton();
        Ipatissier = new javax.swing.JButton();
        Icoiffeur = new javax.swing.JButton();
        Ipeintre = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(5, 1));

        peintre.setText("Peintre");
        peintre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peintreActionPerformed(evt);
            }
        });
        jPanel1.add(peintre);

        patissier.setText("Patissier");
        patissier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patissierActionPerformed(evt);
            }
        });
        jPanel1.add(patissier);

        coiffeur.setText("Coiffeur");
        coiffeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coiffeurActionPerformed(evt);
            }
        });
        jPanel1.add(coiffeur);

        sculpteur.setText("Sculpteur");
        sculpteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sculpteurActionPerformed(evt);
            }
        });
        jPanel1.add(sculpteur);

        marin.setText("Marin");
        marin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marinActionPerformed(evt);
            }
        });
        jPanel1.add(marin);

        getContentPane().add(jPanel1, java.awt.BorderLayout.EAST);

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        ZoneIcon.setText("Image");
        jPanel7.add(ZoneIcon);

        ZoneMetier.setText("Métier");
        jPanel7.add(ZoneMetier);

        jPanel2.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout());

        Resultat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Resultat.setText("Résultat");
        jPanel8.add(Resultat);

        jPanel2.add(jPanel8);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        Titre.setText("Le jeu des métiers");
        jPanel3.add(Titre);

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.GridLayout(5, 1));

        Isculpteur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sculteur.gif"))); // NOI18N
        Isculpteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsculpteurActionPerformed(evt);
            }
        });
        jPanel4.add(Isculpteur);

        Imarin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marin.gif"))); // NOI18N
        Imarin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImarinActionPerformed(evt);
            }
        });
        jPanel4.add(Imarin);

        Ipatissier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patissier.gif"))); // NOI18N
        Ipatissier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IpatissierActionPerformed(evt);
            }
        });
        jPanel4.add(Ipatissier);

        Icoiffeur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coiffeur.gif"))); // NOI18N
        Icoiffeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IcoiffeurActionPerformed(evt);
            }
        });
        jPanel4.add(Icoiffeur);

        Ipeintre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peintre.gif"))); // NOI18N
        Ipeintre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IpeintreActionPerformed(evt);
            }
        });
        jPanel4.add(Ipeintre);

        getContentPane().add(jPanel4, java.awt.BorderLayout.WEST);

        jMenu1.setText("Jeu");

        jMenuItem2.setText("Rejouer");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patissierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patissierActionPerformed
        // TODO add your handling code here:
        ZoneMetier.setText("Patissier");
    }//GEN-LAST:event_patissierActionPerformed

    private void ImarinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImarinActionPerformed
        // TODO add your handling code here:
        ZoneIcon.setText("");
        ZoneIcon.setName("Marin");
        ZoneIcon.setIcon(Imarin.getIcon());
        if(gagne())
            Resultat.setText("GG, ez !");
        else
            Resultat.setText("Non, c'est faux !");
    }//GEN-LAST:event_ImarinActionPerformed

    private void peintreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peintreActionPerformed
        // TODO add your handling code here:
        ZoneMetier.setText("Peintre");
    }//GEN-LAST:event_peintreActionPerformed

    private void coiffeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coiffeurActionPerformed
        // TODO add your handling code here:
        ZoneMetier.setText("Coiffeur");
    }//GEN-LAST:event_coiffeurActionPerformed

    private void sculpteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sculpteurActionPerformed
        // TODO add your handling code here:
        ZoneMetier.setText("Sculpteur");
    }//GEN-LAST:event_sculpteurActionPerformed

    private void marinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marinActionPerformed
        // TODO add your handling code here:
        ZoneMetier.setText("Marin");
    }//GEN-LAST:event_marinActionPerformed

    private void IsculpteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsculpteurActionPerformed
        // TODO add your handling code here:
        ZoneIcon.setText("");
        ZoneIcon.setName("Sculpteur");
        ZoneIcon.setIcon(Isculpteur.getIcon());
        if(gagne())
            Resultat.setText("GG, ez !");
        else
            Resultat.setText("Non, c'est faux !");
    }//GEN-LAST:event_IsculpteurActionPerformed

    private void IpatissierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IpatissierActionPerformed
        // TODO add your handling code here:
        ZoneIcon.setText("");
        ZoneIcon.setName("Patissier");
        ZoneIcon.setIcon(Ipatissier.getIcon());
        if(gagne())
            Resultat.setText("GG, ez !");
        else
            Resultat.setText("Non, c'est faux !");
    }//GEN-LAST:event_IpatissierActionPerformed

    private void IcoiffeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IcoiffeurActionPerformed
        // TODO add your handling code here:
        ZoneIcon.setText("");
        ZoneIcon.setName("Coiffeur");
        ZoneIcon.setIcon(Icoiffeur.getIcon());
        if(gagne())
            Resultat.setText("GG, ez !");
        else
            Resultat.setText("Non, c'est faux !");
    }//GEN-LAST:event_IcoiffeurActionPerformed

    private void IpeintreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IpeintreActionPerformed
        // TODO add your handling code here:
        ZoneIcon.setText("");
        ZoneIcon.setName("Peintre");
        ZoneIcon.setIcon(Ipeintre.getIcon());
        if(gagne())
            Resultat.setText("GG, ez !");
        else
            Resultat.setText("Non, c'est faux !");
    }//GEN-LAST:event_IpeintreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Icoiffeur;
    private javax.swing.JButton Imarin;
    private javax.swing.JButton Ipatissier;
    private javax.swing.JButton Ipeintre;
    private javax.swing.JButton Isculpteur;
    private javax.swing.JLabel Resultat;
    private javax.swing.JLabel Titre;
    private javax.swing.JButton ZoneIcon;
    private javax.swing.JButton ZoneMetier;
    private javax.swing.JButton coiffeur;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton marin;
    private javax.swing.JButton patissier;
    private javax.swing.JButton peintre;
    private javax.swing.JButton sculpteur;
    // End of variables declaration//GEN-END:variables
}
